#!/bin/bash

KUBERNETES_MASTER=$1
NODE_NAME="${NODE_NAME=`hostname -s`}"

if [ -z "$KUBERNETES_MASTER" ]
then
  echo "KUBERNETES_MASTER not set"
else
  echo "KUBERNETES_MASTER=$KUBERNETES_MASTER"
  echo "LABELS=$LABELS"
  if ! grep "/var/lib/kubelet " /proc/self/mountinfo | grep shared; then 
    echo "Making /var/lib/kubelet shared."
    mkdir -p /var/lib/kubelet
    mount --bind /var/lib/kubelet /var/lib/kubelet
    mount --make-shared /var/lib/kubelet
  fi
  rpc.statd
  swapoff -a

  docker rm -f knode
  docker run \
         --name knode \
         -e LABELS="$LABELS" \
         -e KUBERNETES_MASTER="https://$KUBERNETES_MASTER:6443" \
         -e NODE_NAME="$NODE_NAME" \
         -e ETCD_HOST="$KUBERNETES_MASTER" \
         -e ETCD_ENDPOINTS="http://$KUBERNETES_MASTER:4001" \
         -e CLUSTER_CIDR="250.0.0.0/8" \
         -e VAULT_ADDR="http://$KUBERNETES_MASTER:8200" \
         -e VAULT_TOKEN="$VAULT_TOKEN" \
         --net=host \
         --pid=host \
         --privileged=true \
         -p 10250:10250 \
         -v /sys:/sys:rw \
         -v /:/rootfs:ro \
         -v /dev:/dev:rw \
         -v /lib/modules:/lib/modules:ro \
         -v /var/run:/var/run:rw \
         -v /var/lib/docker/:/var/lib/docker:rw \
         -v /var/lib/kubelet/:/var/lib/kubelet:rw,shared \
         -v /var/log:/var/log \
         -d kubernetes-node
fi

