#!/bin/bash

KUBERNETES_MASTER=$1

if [ -z "$KUBERNETES_MASTER" ]
then
  echo "KUBERNETES_MASTER not set"
else
  echo "KUBERNETES_MASTER=$KUBERNETES_MASTER"
  mkdir -p /var/lib/kubelet
  mount --bind /var/lib/kubelet /var/lib/kubelet
  mount --make-shared /var/lib/kubelet
  rpcinfo
  docker run \
         -e LABELS=${LABELS} \
         -p 10250:10250 \
         -e KUBERNETES_MASTER="http://$KUBERNETES_MASTER:8080" \
         -e ETCD_HOST=$KUBERNETES_MASTER \
         --net=host \
         --pid=host \
         --privileged=true \
         -v /sys:/sys:ro \
         -v /:/rootfs:ro \
         -v /var/run:/var/run:rw \
         -v /var/lib/docker/:/var/lib/docker:rw \
         -v /var/lib/kubelet/:/var/lib/kubelet:rw,shared \
         -v /var/log:/var/log \
         -d kubernetes-node
fi

