#!/bin/bash

#sv start register  || exit 1

source /etc/envvars

PRIMARY=`route|grep default|awk '{print $8}'`

exec 2>&1
exec dnsmasq --user=root --interface=$PRIMARY --bind-interfaces --hostsdir=/etc/confd/hosts --domain-needed --keep-in-foreground --log-facility -
