#!/bin/bash

source /etc/envvars

export IP=`ip route get 1 | awk '{print $NF;exit}'`
HOST=`hostname -s`
KUBELET_OPTS="--address=0.0.0.0 \
--hostname_override=$IP \
--cluster_dns=$IP \
--port=10250 \
--api_servers=$KUBERNETES_MASTER \
--containerized=false \
--image-gc-high-threshold=50 \
--image-gc-low-threshold=30 \
--registry-qps=0 \
--hairpin-mode=hairpin-veth \
--serialize-image-pulls=false \
--node-labels=host=${HOST},${LABELS} \
--allow-privileged=true \
--pod-manifest-path=/etc/kubernetes/manifests \
--kube-reserved=cpu=500m,memory=5Mi \
--system-reserved=cpu=100m,memory=1Mi \
--v=2 \
--logtostderr=true"

#setup cgroups
for cgroup in /sys/fs/cgroup/*; do
  if [ -d $cgroup ]; then
    mkdir -p $cgroup/kubepods
  fi
done

exec 2>&1
exec kubelet ${KUBELET_OPTS}
