#!/bin/bash

source /etc/envvars

IP=`ip route get 1 | awk '{print $NF;exit}'`
HOST=`hostname -s`
KUBELET_OPTS="--address=0.0.0.0 \
--hostname_override=$IP \
--cluster_dns=$IP \
--port=10250 \
--api_servers=$KUBERNETES_MASTER \
--containerized=false \
--image-gc-high-threshold=50 \
--image-gc-low-threshold=30 \
--registry-qps=0 \
--hairpin-mode=hairpin-veth \
--serialize-image-pulls=false \
--node-labels=host=${HOST},${LABELS} \
--allow-privileged=true \
--v=2 \
--logtostderr=true"

exec 2>&1
exec kubelet ${KUBELET_OPTS}
