#!/bin/bash

source /etc/envvars

IP=`ip route get 1 | awk '{print $NF;exit}'`
KUBELET_OPTS="--address=0.0.0.0 \
--hostname_override=$IP \
--cluster_dns=$IP \
--port=10250 \
--api_servers=$KUBERNETES_MASTER \
--config=/etc/kubernetes/manifests \
--containerized=false \
--resource-container="" \
--registry-qps=0 \
--hairpin-mode=none \
--v=2 \
--logtostderr=true"

env
exec 2>&1
exec kubelet ${KUBELET_OPTS}
