#!/bin/bash

sv start kubelet  || exit 1

source /etc/envvars

until curl -s localhost:10255/healthz; do echo "Waiting for Kubelet..."; sleep 5; done

export PKI_DIR=/dev/shm/kubernetes
export ROLE=kube-proxy
export USER=system:kube-proxy

KUBE_PROXY_OPTS="\
--hostname-override=$NODE_NAME \
--cluster-cidr "$CLUSTER_CIDR" \
--proxy-mode=ipvs \
--feature-gates=$FEATURE_GATES \
--kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml \
--logtostderr=true \
--v=2 \
"

#API-Server cert and key
mkdir -p $PKI_DIR
if [ ! -f $PKI_DIR/$ROLE-key.pem ]; then
  DATA=$(vault write --format=json kubernetes/issue/$ROLE common_name="$USER" ttl=8760h)
  echo $DATA|jq -r .data.issuing_ca > $PKI_DIR/$ROLE-ca.pem
  echo $DATA|jq -r .data.certificate > $PKI_DIR/$ROLE-cert.pem
  echo $DATA|jq -r .data.private_key > $PKI_DIR/$ROLE-key.pem
fi

kubectl config set-cluster kubernetes \
    --certificate-authority=$PKI_DIR/$ROLE-ca.pem \
    --server=$KUBERNETES_MASTER \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-credentials $USER \
    --client-certificate=$PKI_DIR/$ROLE-cert.pem \
    --client-key=$PKI_DIR/$ROLE-key.pem \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config set-context default \
    --cluster=kubernetes \
    --user=$USER \
    --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml
kubectl config use-context default --kubeconfig=$PKI_DIR/$ROLE-kubeconfig.yml

exec 2>&1
exec kube-proxy ${KUBE_PROXY_OPTS}
