#!/bin/bash

source /etc/envvars
env

IP=`ip route get 1 | awk '{print $NF;exit}'`
KUBE_PROXY_OPTS="--master=$KUBERNETES_MASTER \
--hostname_override=$IP \
--proxy-mode=iptables \
--resource-container="" \
--v=2 \
--logtostderr=true"

exec 2>&1
exec kube-proxy ${KUBE_PROXY_OPTS}
